global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8080'   # spring-cloud-mastery
          - 'host.docker.internal:8082'   # user-service
          - 'host.docker.internal:8481'   # gateway-service

  - job_name: 'dynamic-routing-core'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'host.docker.internal:8085'